name: minetest-clock
channels:
- defaults
dependencies:
- python=3.6.*
- bz2file==0.98
- cython==0.29.*
- pip==10.0.*
- numpy==1.15.*
- jupyter==1.0.*
- matplotlib==3.0.*
- setuptools==39.1.*
- pandas==0.23.*
- pillow==5.3.*
- seaborn==0.9.*
- pytest==3.9.*
- twisted==18.9.*
